### ISSUE TITLE
Failing for PRs from Forks

### ISSUE THREAD

**Issue by DerekRoberts** [DerekRoberts/action-pr-description-add#12]
I'm pretty sure the workflow calling needs to provide specific token rights.  Test and add to directions / readme.

```
steps:
  - name: whatever
    permissions:
      pull-request: write
```

From outside repo:
```
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/DerekRoberts/action-pr-description-add/v0.0.1/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
